// GLOBAL
export const SET_INITIAL_STATE = 'FETCH_INITIAL_STATE';


// USER
export const FETCH_USER = 'FETCH_USER';
export const FETCH_GOOGLE_USER_DETAILS = 'FETCH_GOOGLE_USER_DETAILS';


// CARDS
export const ADD_CARD_TO_USER = 'ADD_CARD_TO_USER';
export const REMOVE_CARD_FROM_USER = 'REMOVE_CARD_FROM_USER';
export const GET_ALL_CARDS = 'GET_ALL_CARDS';

//ERRORS
